StockTrackingMVC/Models/LoginViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace StockTrackingMVC.Models
{
    public class LoginViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Kullanıcı Adı")]
        public string UserName { get; set; }
        [Required]
        [DisplayName("Kullanıcı Şifresi")]
        public string UserPassword { get; set; }

        public bool KeepLoggedIn { get; set; }
    }
}

StockTrackingMVC/Controllers/AccessController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StockTrackingMVC.Data;
using StockTrackingMVC.Models;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace StockTrackingMVC.Controllers
{
	public class AccessController : Controller
	{
		private readonly StockTrackingDBContext _dbcontext;

		public AccessController(StockTrackingDBContext dbcontext)
		{
			_dbcontext = dbcontext;
		}

		public IActionResult Login()
		{
			return View(new LoginViewModel());
		}

		public User GetUserByCredentials(string username, string password)
		{
			return _dbcontext.Users.SingleOrDefault(u => u.UserName == username && u.UserPassword == password);
		}

		[HttpPost]
		public async Task<IActionResult> Login(LoginViewModel loginViewModel)
		{
			if (ModelState.IsValid)
			{
				User foundUser = GetUserByCredentials(loginViewModel.UserName, loginViewModel.UserPassword);

				if (foundUser != null)
				{
					var claims = new List<Claim>
					{
						new Claim(ClaimTypes.Name, foundUser.UserName),
					};

					if (!string.IsNullOrEmpty(foundUser.UserType))
					{
						claims.Add(new Claim(ClaimTypes.Role, foundUser.UserType));
					}

					var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

					AuthenticationProperties authProperties = null;

					if (loginViewModel.KeepLoggedIn)
					{
						authProperties = new AuthenticationProperties
						{
							IsPersistent = true,
							ExpiresUtc = DateTimeOffset.UtcNow.AddDays(30)
						};
					}
					else
					{
						authProperties = new AuthenticationProperties
						{
							IsPersistent = false
						};
					}

					await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity), authProperties);

					return RedirectToAction("Index", "Home");
				}

				ViewData["ValidateMessage"] = "Invalid username or password.";
			}
			return View(loginViewModel);
		}

		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
			return RedirectToAction("Login");
		}
	}
}

StockTrackingMVC/Views/Access/Login.cshtml
@model StockTrackingMVC.Models.LoginViewModel;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StockTrackingMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StockTrackingTheme.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <div class="container d-flex align-items-center justify-content-center vh-100">
        <div class="card w-50">
            <div class="card-body">
                <h1 class="text-center mb-4">Giriş</h1>
                <form asp-controller="Access" asp-action="Login" method="post">
                    <div class="mb-3">
                        <label for="UserName" class="form-label">İsim</label>
                        <input type="text" class="form-control" id="UserName" name="UserName" placeholder="İsim" asp-for="UserName" required>
                    </div>
                    <div class="mb-3">
                        <label for="UserPassword" class="form-label">Şifre</label>
                        <input type="password" class="form-control" id="UserPassword" name="UserPassword" placeholder="Şifre" asp-for="UserPassword" required>
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="KeepLoggedIn" name="KeepLoggedIn" asp-for="KeepLoggedIn">
                        <label class="form-check-label" for="KeepLoggedIn">Beni Hatırla</label>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Giriş Yap</button>
                </form>
                @if (ViewData["ValidateMessage"] != null)
                {
                    <div class="text-center mt-3">
                        <label class="text-primary-emphasis">@ViewData["ValidateMessage"]</label>
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>