StockTrackingMVC/Controllers/LogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StockTrackingMVC.Data;
using StockTrackingMVC.Models;
using System.Drawing.Printing;

namespace StockTrackingMVC.Controllers
{
	[Authorize]
	public class LogController : Controller
	{
		private readonly StockTrackingDBContext _dbcontext;
		public LogController(StockTrackingDBContext dBContext)
		{
			_dbcontext = dBContext;
		}
		public IActionResult Index(string searchQuery, int page = 1, int pageSize = 10)
		{
			IEnumerable<Log> objLogList = _dbcontext.Logs;
			if (!string.IsNullOrEmpty(searchQuery))
			{
				objLogList = objLogList.Where(p => p.LogUser.Contains(searchQuery, StringComparison.OrdinalIgnoreCase));
			}
			int totalLogs = objLogList.Count();

			int totalPages = (int)Math.Ceiling((double)totalLogs / pageSize);

			page = Math.Max(1, Math.Min(page, totalPages));

			int skipCount = (page - 1) * pageSize;

			var logs = objLogList
				.OrderByDescending(log => log.LogTime)
				.Skip(skipCount)
				.Take(pageSize)
				.ToList();

			ViewBag.Logs = logs;
			ViewBag.CurrentPage = page;
			ViewBag.TotalPages = totalPages;
			return View();

		}
	}
}

StockTrackingMVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StockTrackingMVC.Data;
using StockTrackingMVC.Models;
using System.Drawing.Printing;

namespace StockTrackingMVC.Controllers
{
	[Authorize]
	public class ProductController : Controller
	{
		private readonly StockTrackingDBContext _dbcontext;
		public ProductController(StockTrackingDBContext dbcontext)
		{
			_dbcontext = dbcontext;
		}
		public IActionResult Index(string searchQuery, int page = 1, int pageSize = 10)
		{
			var GetProductsFromDatabase = _dbcontext.Products.Include(p => p.Category);
			IEnumerable<Product> objProductList = GetProductsFromDatabase;

			if (!string.IsNullOrEmpty(searchQuery))
			{
				objProductList = objProductList.Where(p => p.ProductName.Contains(searchQuery, StringComparison.OrdinalIgnoreCase));
			}
			int totalLogs = objProductList.Count();

			int totalPages = (int)Math.Ceiling((double)totalLogs / pageSize);

			page = Math.Max(1, Math.Min(page, totalPages));

			int skipCount = (page - 1) * pageSize;

			var products = objProductList
				.OrderByDescending(product => product.ProductName)
				.Skip(skipCount)
				.Take(pageSize)
				.ToList();

			ViewBag.Products = products;
			ViewBag.CurrentPage = page;
			ViewBag.TotalPages = totalPages;
			return View();
		}
		//GET
		[Authorize]
		public IActionResult Add()
		{
			ViewBag.Categories = _dbcontext.Categories.ToList();
			return View();
		}

		//POST
		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Add(Product obj)
		{
			if (ModelState.IsValid)
			{
				bool productExists = _dbcontext.Products.Any(p => p.ProductName == obj.ProductName);

				if (productExists)
				{
					ModelState.AddModelError("ProductName", "Bu ürün zaten mevcut.");
					ViewBag.Categories = _dbcontext.Categories.ToList();
					return View(obj);
				}
				_dbcontext.Products.Add(obj);
				var message = User.Identity.Name + " ürün ekledi : " + obj.ProductName;
				var logEntry = new Log
				{
					LogUser = User.Identity.Name,
					LogMessage = message,
					LogTime = DateTime.Now
				};
				_dbcontext.Logs.Add(logEntry);
				TempData["success"] = "Ürün başarıyla eklendi";
				_dbcontext.SaveChanges();
				return RedirectToAction("Index");
			}
			ViewBag.Categories = _dbcontext.Categories.ToList();
			return View(obj);
		}

		//GET
		[Authorize]
		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var productFromDb = _dbcontext.Products.Find(id);
			if (productFromDb == null)
			{
				return NotFound();
			}
			ViewBag.Categories = _dbcontext.Categories.ToList();
			return View(productFromDb);
		}

		//POST
		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Product obj)
		{
			if (ModelState.IsValid)
			{
				_dbcontext.Products.Update(obj);
				var message = User.Identity.Name + " ürün güncelledi : " + obj.ProductName;
				var logEntry = new Log
				{
					LogUser = User.Identity.Name,
					LogMessage = message,
					LogTime = DateTime.Now
				};
				_dbcontext.Logs.Add(logEntry);
				_dbcontext.SaveChanges();
				TempData["success"] = "Ürün başarıyla güncellendi";
				return RedirectToAction("Index");
			}
			var value = ModelState.Values.SelectMany(v => v.Errors);
			// If the ModelState is not valid, return the Edit view with the model data
			ViewBag.Categories = _dbcontext.Categories.ToList();
			return View("Edit", obj);
		}


		//GET
		[Authorize]
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var productFromDb = _dbcontext.Products.Find(id);
			if (productFromDb == null)
			{
				return NotFound();
			}
			ViewBag.Categories = _dbcontext.Categories.ToList();
			return View(productFromDb);
		}

		//POST
		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeletePOST(int? id)
		{
			var productFromDb = _dbcontext.Products.Find(id);
			if (productFromDb == null)
			{
				return NotFound();
			}
			_dbcontext.Products.Remove(productFromDb);
			var message = User.Identity.Name + " ürün sildi : " + productFromDb.ProductName;
			var logEntry = new Log
			{
				LogUser = User.Identity.Name,
				LogMessage = message,
				LogTime = DateTime.Now
			};
			_dbcontext.Logs.Add(logEntry);
			_dbcontext.SaveChanges();
			ViewBag.Categories = _dbcontext.Categories.ToList();
			TempData["success"] = "Ürün başarıyla silindi";
			return RedirectToAction("Index");
		}
		[Authorize]
		public IActionResult Sell(int id)
		{
			var productFromDb = _dbcontext.Products.Find(id);
			if (productFromDb == null)
			{
				return NotFound();
			}

			// Reduce the product amount by one if it's greater than zero
			if (productFromDb.ProductAmount > 0)
			{
				productFromDb.ProductAmount--;
				var message = User.Identity.Name + " ürün sattı : " + productFromDb.ProductName;
				var logEntry = new Log
				{
					LogUser = User.Identity.Name,
					LogMessage = message,
					LogTime = DateTime.Now
				};
				_dbcontext.Logs.Add(logEntry);
				_dbcontext.SaveChanges();
			}
			TempData["success"] = "Ürün başarıyla satıldı";
			return RedirectToAction("Index");
		}
	}
}

StockTrackingMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StockTrackingMVC.Data;
using StockTrackingMVC.Models;
using System.Drawing.Printing;

namespace StockTrackingMVC.Controllers
{
	[Authorize]
	public class UserController : Controller
	{
		private readonly StockTrackingDBContext _dbcontext;
		public UserController(StockTrackingDBContext dbcontext)
		{
			_dbcontext = dbcontext;
		}
		public IActionResult Index(string searchQuery, int page = 1, int pageSize = 10)
		{
			IEnumerable<User> objUserList = _dbcontext.Users;
			if (!string.IsNullOrEmpty(searchQuery))
			{
				objUserList = objUserList.Where(p => p.UserName.Contains(searchQuery, StringComparison.OrdinalIgnoreCase));
			}

			int totalLogs = objUserList.Count();

			int totalPages = (int)Math.Ceiling((double)totalLogs / pageSize);

			page = Math.Max(1, Math.Min(page, totalPages));

			int skipCount = (page - 1) * pageSize;

			var users = objUserList
				.OrderByDescending(user => user.UserName)
				.Skip(skipCount)
				.Take(pageSize)
				.ToList();

			// Pass the logs and pagination information to the view
			ViewBag.Logs = users;
			ViewBag.CurrentPage = page;
			ViewBag.TotalPages = totalPages;
			return View(objUserList);
		}

		//GET
		public IActionResult Add()
		{
			ViewBag.Users = _dbcontext.Users.ToList();
			return View();
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Add(User obj)
		{
			if (ModelState.IsValid)
			{
				bool userExists = _dbcontext.Users.Any(p => p.UserName == obj.UserName);

				if (userExists)
				{
					ModelState.AddModelError("UserName", "Bu kullanıcı zaten mevcut.");
					ViewBag.Users = _dbcontext.Users.ToList();
					return View(obj);
				}
				string selectedUserType = Request.Form["UserType"];

				obj.UserType = selectedUserType;

				var message = User.Identity.Name + " kullanıcı ekledi : " + obj.UserName + ", tür : " + obj.UserType;
				var logEntry = new Log
				{
					LogUser = User.Identity.Name,
					LogMessage = message,
					LogTime = DateTime.Now
				};
				_dbcontext.Logs.Add(logEntry);
				_dbcontext.Users.Add(obj);
				_dbcontext.SaveChanges();
				TempData["success"] = "Kullanıcı başarıyla eklendi";
				return RedirectToAction("Index");
			}

			ViewBag.Users = _dbcontext.Users.ToList();
			return View(obj);
		}


		//GET
		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var userFromDb = _dbcontext.Users.Find(id);
			if (userFromDb == null)
			{
				return NotFound();
			}
			ViewBag.Users = _dbcontext.Users.ToList();
			return View(userFromDb);
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(User obj)
		{
			if (ModelState.IsValid)
			{
				// Select aracı için kullanıcı tipi
				string selectedUserType = Request.Form["UserType"];

				// Kullanıcı tipi atama
				obj.UserType = selectedUserType;

				var message = User.Identity.Name + " kullanıcı güncelledi : " + obj.UserName + ", tür : " + obj.UserType;
				var logEntry = new Log
				{
					LogUser = User.Identity.Name,
					LogMessage = message,
					LogTime = DateTime.Now
				};
				_dbcontext.Logs.Add(logEntry);

				_dbcontext.Users.Update(obj);
				_dbcontext.SaveChanges();
				TempData["success"] = "Kullanıcı başarıyla güncellendi";
				return RedirectToAction("Index");
			}

			ViewBag.Users = _dbcontext.Users.ToList();
			return View(obj);
		}

		//GET
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var userFromDb = _dbcontext.Users.Find(id);
			if (userFromDb == null)
			{
				return NotFound();
			}
			ViewBag.Users = _dbcontext.Users.ToList();
			return View(userFromDb);
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeletePOST(int? id)
		{
			var userFromDb = _dbcontext.Users.Find(id);
			if (userFromDb == null)
			{
				return NotFound();
			}
			var message = User.Identity.Name + " kullanıcı sildi : " + userFromDb.UserName + ", tür : " + userFromDb.UserType;
			var logEntry = new Log
			{
				LogUser = User.Identity.Name,
				LogMessage = message,
				LogTime = DateTime.Now
			};
			_dbcontext.Logs.Add(logEntry);
			_dbcontext.Users.Remove(userFromDb);
			_dbcontext.SaveChanges();
			ViewBag.Users = _dbcontext.Users.ToList();
			TempData["success"] = "Kullanıcı başarıyla silindi";
			return RedirectToAction("Index");
		}
	}
}

StockTrackingMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockTrackingMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StockTrackingMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StockTrackingTheme.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockTrackingMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Product" asp-action="Index">Ürün İşlemleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="LogOut">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StockTrackingMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StockTrackingMVC/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockTrackingMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StockTrackingMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StockTrackingTheme.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockTrackingMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" id="productDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-box-seam"></i> Ürün İşlemleri
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="productDropdown">
                                <li><a class="dropdown-item text-dark"  asp-controller="Product" asp-action="Index">Ürünleri İncele</a></li>
                                <li><a class="dropdown-item text-dark"  asp-controller="Product" asp-action="Add">Ürün Ekle</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-people"></i> Kullanıcı İşlemleri
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="userDropdown">
                                <li><a class="dropdown-item text-dark" asp-controller="User" asp-action="Index">Kullanıcıları İncele</a></li>
                                <li><a class="dropdown-item text-dark" asp-controller="User" asp-action="Add">Kullanıcı Ekle</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Log" asp-action="Index"><i class="bi bi-card-list"></i> Kayıt Girdileri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="LogOut"><i class="bi bi-door-open"></i> Çıkış Yap</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <span class="nav-link text-light">Kullanıcı : @User.Identity.Name</span>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StockTrackingMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StockTrackingMVC/Views/Shared/_LayoutKullanici.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockTrackingMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StockTrackingMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StockTrackingTheme.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockTrackingMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" id="productDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-box-seam"></i> Ürün İşlemleri
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="productDropdown">
                                <li><a class="dropdown-item text-dark" asp-controller="Product" asp-action="Index">Ürünleri İncele</a></li>
                                <li><a class="dropdown-item text-dark" asp-controller="Product" asp-action="Add">Ürün Ekle</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="LogOut"><i class="bi bi-door-open"></i> Çıkış Yap</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <span class="nav-link text-light">Kullanıcı : @User.Identity.Name</span>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StockTrackingMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StockTrackingMVC/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}